#!/usr/bin/env python3
from __future__ import annotations

import argparse
import sqlite3
from pathlib import Path
from typing import Iterable


def fmt_int(n: int) -> str:
    return f"{n:,}"


def fmt_pct(num: int, den: int) -> str:
    return "n/a" if den <= 0 else f"{(100.0 * num / den):.2f}\\%"


def tex_escape(s: str) -> str:
    return (
        s.replace("\\", "\\textbackslash{}")
        .replace("&", "\\&")
        .replace("%", "\\%")
        .replace("_", "\\_")
        .replace("#", "\\#")
        .replace("{", "\\{")
        .replace("}", "\\}")
    )


def q(conn: sqlite3.Connection, sql: str, params: Iterable[object] = ()) -> list[sqlite3.Row]:
    return conn.execute(sql, tuple(params)).fetchall()


def build_temp_views(conn: sqlite3.Connection) -> None:
    conn.executescript(
        """
        DROP VIEW IF EXISTS audited;
        DROP VIEW IF EXISTS per_skill_flags;
        DROP VIEW IF EXISTS per_skill_strict;
        DROP VIEW IF EXISTS per_repo_strict;

        CREATE TEMP VIEW audited AS
        SELECT DISTINCT skill_id
        FROM skill_security_scanner_results;

        CREATE TEMP VIEW per_skill_flags AS
        SELECT
            s.id AS skill_pk,
            s.source,
            s.skill_id,
            s.name,
            s.installs,
            COALESCE(g.stars, 0) AS stars,
            MAX(CASE WHEN r.scanner_slug = 'agent-trust-hub' AND r.status = 'fail' THEN 1 ELSE 0 END) AS fail_agent_trust_hub,
            MAX(CASE WHEN r.scanner_slug = 'snyk' AND r.status = 'fail' THEN 1 ELSE 0 END) AS fail_snyk,
            MAX(CASE WHEN r.scanner_slug = 'socket' AND r.status = 'fail' THEN 1 ELSE 0 END) AS fail_socket
        FROM skills s
        JOIN audited a
          ON a.skill_id = s.id
        LEFT JOIN github_repo_metadata g
          ON g.source = s.source
        LEFT JOIN skill_security_scanner_results r
          ON r.skill_id = s.id
        GROUP BY s.id, s.source, s.skill_id, s.name, s.installs, g.stars;

        CREATE TEMP VIEW per_skill_strict AS
        SELECT
            *,
            CASE WHEN (fail_agent_trust_hub + fail_snyk + fail_socket) > 0 THEN 1 ELSE 0 END AS is_malicious_strict
        FROM per_skill_flags;

        CREATE TEMP VIEW per_repo_strict AS
        SELECT
            source,
            MAX(stars) AS stars,
            MAX(installs) AS installs,
            MAX(is_malicious_strict) AS repo_is_malicious_strict
        FROM per_skill_strict
        GROUP BY source;
        """
    )


def scanner_rows(conn: sqlite3.Connection) -> list[tuple[str, int, int, int, str]]:
    rows = q(
        conn,
        """
        SELECT
            scanner_slug,
            SUM(CASE WHEN status='pass' THEN 1 ELSE 0 END) AS pass_n,
            SUM(CASE WHEN status='fail' THEN 1 ELSE 0 END) AS fail_n,
            COUNT(*) AS total_n
        FROM skill_security_scanner_results
        GROUP BY scanner_slug
        ORDER BY scanner_slug;
        """,
    )
    out = []
    for r in rows:
        total = int(r["total_n"] or 0)
        passes = int(r["pass_n"] or 0)
        fails = int(r["fail_n"] or 0)
        out.append((str(r["scanner_slug"]), total, passes, fails, fmt_pct(fails, total)))
    return out


def detection_rows(conn: sqlite3.Connection) -> list[tuple[str, int, int, str]]:
    rows = q(
        conn,
        """
        SELECT 'Skills (overall)' AS segment, COUNT(*) AS n, SUM(is_malicious_strict) AS mal
        FROM per_skill_strict
        UNION ALL
        SELECT 'Skills (stars > 1000)', COUNT(*), SUM(is_malicious_strict)
        FROM per_skill_strict
        WHERE stars > 1000
        UNION ALL
        SELECT 'Skills (installs > 1000)', COUNT(*), SUM(is_malicious_strict)
        FROM per_skill_strict
        WHERE installs > 1000
        UNION ALL
        SELECT 'Repositories (overall)', COUNT(*), SUM(repo_is_malicious_strict)
        FROM per_repo_strict
        UNION ALL
        SELECT 'Repositories (stars > 1000)', COUNT(*), SUM(repo_is_malicious_strict)
        FROM per_repo_strict
        WHERE stars > 1000
        UNION ALL
        SELECT 'Repositories (installs > 1000)', COUNT(*), SUM(repo_is_malicious_strict)
        FROM per_repo_strict
        WHERE installs > 1000;
        """,
    )
    out = []
    for r in rows:
        total = int(r["n"] or 0)
        malicious = int(r["mal"] or 0)
        out.append((str(r["segment"]), total, malicious, fmt_pct(malicious, total)))
    return out


def render_scanner_table(rows: list[tuple[str, int, int, int, str]], db_path: Path) -> str:
    lines = [
        "% Auto-generated by scripts/tables/generate_skillsh_security_tables.py",
        f"% Source DB: {db_path}",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Scanner comparison on Skills.sh manual crawl dataset}",
        "\\label{tab:skills_sh_scanner_comparison}",
        "\\begin{tabular}{lrrrr}",
        "\\toprule",
        "Scanner & Skills Scanned & Pass & Fail & Fail Rate \\\\",
        "\\midrule",
    ]
    for slug, total, passes, fails, rate in rows:
        lines.append(f"{tex_escape(slug)} & {fmt_int(total)} & {fmt_int(passes)} & {fmt_int(fails)} & {rate} \\\\")
    lines.extend(["\\bottomrule", "\\end{tabular}", "\\end{table}", ""])
    return "\n".join(lines)


def render_detection_table(rows: list[tuple[str, int, int, str]], db_path: Path) -> str:
    lines = [
        "% Auto-generated by scripts/tables/generate_skillsh_security_tables.py",
        f"% Source DB: {db_path}",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{Strict malicious detection rates for skills and repositories (repository malicious if at least one skill is malicious)}",
        "\\label{tab:skills_sh_detection_rates_strict}",
        "\\begin{tabular}{lrrr}",
        "\\toprule",
        "Segment & Total & Malicious & Detection Rate \\\\",
        "\\midrule",
    ]
    for segment, total, malicious, rate in rows:
        lines.append(f"{tex_escape(segment)} & {fmt_int(total)} & {fmt_int(malicious)} & {rate} \\\\")
    lines.extend(["\\bottomrule", "\\end{tabular}", "\\end{table}", ""])
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate the two Skills.sh RQ2 security tables used by RQ2.tex.")
    ap.add_argument("--db", default="../data/rq2_malicious_classification/skills_sh_security_scan_manual_crawl.db")
    ap.add_argument("--out-dir", default="tables")
    args = ap.parse_args()

    db_arg_path = Path(args.db)
    db_path = db_arg_path.resolve()
    out_dir = Path(args.out_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    conn = sqlite3.connect(str(db_path))
    conn.row_factory = sqlite3.Row
    try:
        conn.execute("PRAGMA temp_store=MEMORY")
        build_temp_views(conn)
        scanners = scanner_rows(conn)
        detections = detection_rows(conn)
    finally:
        conn.close()

    scanner_path = out_dir / "skillsh_security_scanners.tex"
    scans_path = out_dir / "skillsh_security_scans.tex"
    scanner_path.write_text(render_scanner_table(scanners, db_arg_path), encoding="utf-8")
    scans_path.write_text(render_detection_table(detections, db_arg_path), encoding="utf-8")

    print(f"Wrote: {scanner_path}")
    print(f"Wrote: {scans_path}")


if __name__ == "__main__":
    main()
